server:
  port: 8080
nameaaaaaa: aa #在其他位置@Value获取
spring: # mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/company?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  jpa:  #datasourlJPA配置
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

