spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /zms
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.java.zms.Domain # 注意：对应实体类的路径

