spring:
  profiles:
    active: dev
    #静态文件路径
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: html
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
   # reactive:
   #   chunked-mode-view-names: HTML
   #   full-mode-view-names: HTML
server:
  servlet:
    context-path: /zms
mybatis:
  mapper-locations: mapper/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.java.zms.Domain # 注意：对应实体类的路径

